name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Packaging and Deloying
      env:
           GITHUB_USERNAME: x-access-token
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      run: | 
          mkdir Spring-Project
          cd Spring-Project
          mkdir bin
          cd ..
          cp  target/docker-spring-data-rest.jar Spring-Project/bin/
          cp -r config Spring-Project/
          cp -r script Spring-Project/
          cp -r security-key Spring-Project/
          cd Spring-Project
          zip -r ../artifact.zip config script security-key bin 
          mvn deploy:deploy-file --settings config/settings.xml -Dtoken=$env.GITHUB_TOKEN -Durl=https://maven.pkg.github.com/AishwaryaPedemane/master -DrepositoryId=github -Dfile=Spring-Project -DpomFile=SpringRestData/pom.xml -DgroupId=com.example -DartifactId=SpringRestData -Dpackaging=zip -e
          echo " Packaged successfully and Deployed"
