name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configuring Amazon Corretto Java
      run: |
            wget https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
            sudo apt-get update 
            sudo apt-get install java-common
            sudo dpkg --install java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
            sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-amazon-corretto
            java -version
            sudo update-alternatives --config java 
        
    - name: Build with Maven
      run: |
           mvn -B package --file pom.xml
           
    - name: Deploy to Github Package Registry
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      run: |
            mvn --version
            mvn --settings .m2/settings.xml -Dregistry=https://maven.pkg.github.com/AishwaryaPedemane -Dtoken=5ff1615522fb334292a191e610bb03fa69ccac01 deploy -e

           
           
      
      
    
    

