name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configuring Amazon Corretto Java
      run: |
            wget https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
            sudo apt-get update 
            sudo apt-get install java-common
            sudo dpkg --install java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
            sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-amazon-corretto
            java -version
            sudo update-alternatives --config java 
        
    - name: Build with Maven
      run: |
           mvn -B package --file pom.xml
           
    
            
    - name: Packaging
     
      run: | 
         
          mkdir SpringProject
          cp target/docker-spring-data-rest.jar  SpringProject/
          cd SpringProject/
          cd ..
          pwd
          ls -ll
          mkdir bin
          cd ..
          
          zip -r SpringProject/
          cd SpringProject/ 
          ls -ll
          echo " Packaged successfully."
          mvn --version
          
    
    - uses: actions/upload-artifact@v1
      with:
       name: artifact
       path: SpringProject/
   
    - name: Build
      env:
           GITHUB_USERNAME: x-access-token
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           mvn --settings .m2/settings.xml -Dtoken=$env.GITHUB_TOKEN -Dfile=SpringProject/ -DpomFile=pom.xml deploy -e
           
            
            
       
    
       
    
           
    
    
    
      

           
           
      
      
    
    

